Update header.html
MyroniukIS/ariva-team-filmoteka-project pull request #3
Opened 2021-10-08 12:36 UTC by ttuluk

разметила

2021-10-08 12:46 UTC, MyroniukIS requested changes

2021-10-08 12:46 UTC, MyroniukIS commented on src/partials/header.html
> +    <svg class="search-icon" width="20" height="20"></svg>
думаю тут треба зробити кнопкою, щоб можна було по сабміту форму відправити...  хто там буде слухач вішати

2021-10-08 12:46 UTC, MyroniukIS commented on src/partials/header.html
> +      <a class="logo link" href="./index.html">Filmoteka</a>
тут ще має бути зліва іконка і мабуть іконку і текст filmoteka треба в один контейнер, щоб потім по них клік проходив, або іконку прямо в ссилку запхнути

2021-10-08 12:46 UTC, MyroniukIS commented on src/partials/header.html
> +      <a class="logo link" href="./index.html">Filmoteka</a>
Вобшєм, зроби один дів на іконку і текст і потім клік буде в межах діва, по айдішніку

2021-10-09 14:58 UTC, MyroniukIS commented on src/sass/base/_header.scss
> +    margin-bottom: 40px;
на границях між розширеннями, ну ти поняла

2021-10-09 15:01 UTC, MyroniukIS commented on src/sass/base/_header.scss
> +  text-align: center;
text-align: center;
нічого не робить

2021-10-09 15:02 UTC, MyroniukIS commented on src/sass/base/_header.scss
> +  text-align: center;
text-align: center; 
теж нічого не робить

2021-10-09 15:07 UTC, MyroniukIS commented on src/sass/base/_header.scss
> +    width: 336px;
на мобілці - 280, а далі вже 336

2021-10-09 15:11 UTC, MyroniukIS commented on src/sass/base/_header.scss
> +.form-btn {
cursor: pointer

2021-10-09 15:17 UTC, MyroniukIS commented on src/sass/base/_header.scss
> +  margin-right: 40px;
зроби тут 39, бо на мобілці якраз на 320-ти скаче

2021-10-09 15:19 UTC, MyroniukIS commented on src/partials/header.html
> +      <a class="logo link" href="./index.html"><svg class="logo__icon icon" width="24" height="24"><use href="./images/icons/icons.svg#icon-film"></use></svg>Filmoteka</a>
на мобілці слово фільмотєка забирай

2021-10-09 15:22 UTC, MyroniukIS commented on src/partials/header.html
> +      <a class="logo link" href="./index.html">Filmoteka</a>
+++

2021-10-09 20:55 UTC, ttuluk commented on src/partials/header.html
> +    <svg class="search-icon" width="20" height="20"></svg>
кнопку убрала и добавила текст

2021-10-10 11:29 UTC, MyroniukIS commented on src/partials/header.html
> +    <svg class="search-icon" width="20" height="20"></svg>
+

2021-10-10 11:30 UTC, MyroniukIS commented on src/partials/header.html
> +    <svg class="search-icon" width="20" height="20"></svg>
ok

2021-10-10 11:43 UTC, MyroniukIS commented on src/js/site-nav.js
> +const libraryLink = document.getElementById('library');
їх треба в рефи src/js/refs.js

2021-10-10 11:43 UTC, MyroniukIS commented on src/js/site-nav.js
> +const libraryLink = document.getElementById('library');
а сам файл в src/js/components/site-nav.js

2021-10-10 11:55 UTC, MyroniukIS commented on src/sass/base/_header.scss
> +.form-btn {
не треба вже, ок

2021-10-10 11:55 UTC, MyroniukIS submitted a review, later dismissed

2021-10-10 13:20 UTC, merged